### ISSUE TITLE
Native Messaging sending a message that is 1668248176 bytes long.

### ISSUE THREAD

**Issue by rbuzatu90** [hsanson/chrome-pass#18]
On macOS with latest chrome, when doing debugging I get this:
[23211:39427:0724/110957.334030:ERROR:native_message_process_host.cc(277)] Native Messaging host tried sending a message that is 1668248176 bytes long.

I can see my files in the menu but as soon as click on one of them the menu disappears and the password is not copied.
Also I'm not sure on how the structure of the files and content of the files should be. Right now I have just one line with the password.

**Comment by hsanson** [comment]
Seems this is due to the way MacOS starts the chrome process...  Not sure this is something that can be work around by the native client or the plugin. For some reason, it seems that Chrome is sending losts of data to the native application.

   - https://stackoverflow.com/questions/20329094/native-messaging-host-tried-sending-a-message-that-is-460151579-bytes-long

**Comment by hsanson** [comment]
Closed due to inactivity.

**Comment by robinma** [comment]
解决了吗？现有还有这个问题
