### ISSUE TITLE
Auto-focusing password field no longer works in master

### ISSUE THREAD

**Issue by NateEag** [hsanson/chrome-pass#20]
I just updated my local checkout to current master to get the changes for Apple's App Store Connect login form.

When I did so, I discovered that I had lost the password field auto-focus behavior [I originally implemented](https://github.com/hsanson/chrome-pass/pull/17).

Reverting [this commit](https://github.com/hsanson/chrome-pass/commit/51144e4e817057382ea23ca2fac8f13286d1b3d0) makes it work again for me.

I'm using Google Chrome on OS X, version 72.0.3626.81.

The commit I reverted says "Fix password field focus." What motivated that change? I'm guessing it fixed the focus behavior in a browser other than Chrome?

**Comment by hsanson** [comment]
@NateEag thanks for the report, I will revert this change so let me know if it works for you.

I find interesting you mention Apple's App Store as affected since I was actually trying to make this plugin work better with Apple pages, specially the app store and developer pages. 

When the plugin auto-fills the user/pass in these pages, the submit button is never enabled. I need to focus each field, write a letter, and subsequently delete it in order to get the submit button enabled. So far I have been unable to get a good solution to avoid the extra steps.

**Comment by NateEag** [comment]
Heh, yes, the App Store Connect login has been annoying me for a while too.

I discovered your fix for it because I was thinking about fixing it myself - just turned out you'd already done it, so thanks!

I can confirm the reversion is working for me, so thanks for that. The focus loss was happening to every form I used, not just the App Store Connect one.

I've been doing the exact same routine where I add a space then delete it to activate the submit button on the App Store Connect login page. I tried some monkeying with the form too, but like you so far I haven't found a way to enable the submit button automatically.

If I do manage to come up with an improvement, I'll definitely submit it to the project.
